# Generated by Django 5.0.7 on 2024-10-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0003_studentlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'ADVANCED OBJECT ORIENTED PROGRAMMING'), ('CTOD', 'COMPUTATIONAL THINKING FOR OBJECT DESIGN'), ('CTOOD', 'COMPUTATIONAL THINKING FOR OBJECT ORIENTED DESIGN'), ('PFSD', 'PYTHON FULL STACK WEB DEVELOPMENT'), ('DBMS', 'DATABASE MANAGEMENT SYSTEM'), ('DSS', 'DATA SCIENCE AND STATISTICS')], max_length=50)),
                ('section', models.CharField(choices=[('S11', 'SECTION S11'), ('S12', 'SECTION S12'), ('S13', 'SECTION S13'), ('S14', 'SECTION S14'), ('S15', 'SECTION S15'), ('S21', 'SECTION S21'), ('S22', 'SECTION S22'), ('S23', 'SECTION S23'), ('S24', 'SECTION S24'), ('S25', 'SECTION S25')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'ADVANCED OBJECT ORIENTED PROGRAMMING'), ('CTOD', 'COMPUTATIONAL THINKING FOR OBJECT DESIGN'), ('CTOOD', 'COMPUTATIONAL THINKING FOR OBJECT ORIENTED DESIGN'), ('PFSD', 'PYTHON FULL STACK WEB DEVELOPMENT'), ('DBMS', 'DATABASE MANAGEMENT SYSTEM'), ('DSS', 'DATA SCIENCE AND STATISTICS')], max_length=50)),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
    ]
