# Generated by Django 5.0.7 on 2024-10-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
