# Generated by Django 5.0.7 on 2024-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('textfield', models.TextField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='Register_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
